name: Terraform & Docker ECR Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 4. Terraform init
      - name: Terraform Init
        working-directory: ./terraform   # relative path in repo
        run: terraform init
      
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
