name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Show repo structure for debugging
      - name: Debug: List repo files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo root:"
          ls -l
          echo "Check if terraform folder exists:"
          ls -l terraform || echo "terraform folder not found!"

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5  # stable version

      # 5. Terraform init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 6. Terraform apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
