name: Terraform + Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # 4. Terraform init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5. Terraform apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # 6. Get ECR repository URL
      - name: Get ECR URL
        id: ecr
        working-directory: terraform
        run: echo "ECR_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV

      # 7. Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ECR_URL }}

      # 8. Build Docker image
      - name: Build Docker image
        run: docker build -t dev-react-frontend:latest .

      # 9. Tag Docker image for ECR
      - name: Tag Docker image
        run: docker tag dev-react-frontend:latest ${{ env.ECR_URL }}:latest

      # 10. Push Docker image
      - name: Push Docker image
        run: docker push ${{ env.ECR_URL }}:latest
