name: Terraform + Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-docker:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

     # Get ECR URL cleanly
      - name: Get ECR URL
        id: ecr
        working-directory: terraform
        run: |
          # Get Terraform output in JSON
          ECR_URL=$(terraform output -json ecr_repository_url | jq -r '.')
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
          echo "ECR_URL=$ECR_URL"

# Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ECR_URL }}
      
            # 8. Build Docker image
            - name: Build Docker image
              run: docker build -t dev-react-frontend:latest .

      # 9. Tag Docker image for ECR
      - name: Tag Docker image
        run: docker tag dev-react-frontend:latest ${{ env.ECR_URL }}:latest

      # 10. Push Docker image to ECR
      - name: Push Docker image
        run: docker push ${{ env.ECR_URL }}:latest

      # 11. Optional future steps: e.g., deploy to ECS or update service
      # - name: Deploy to ECS
      #   run: |
      #     echo "Here you can add future steps like ECS service update"
