name: React CI/CD with Terraform & ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: dev-scrum-frontend

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3️⃣ Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Login to ECR
      - name: Login to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names $ECR_REPO_NAME \
            --query "repositories[0].repositoryUri" \
            --output text)
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
          aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS --password-stdin $ECR_URI

      # 5️⃣ Build and push Docker image
      - name: Build and Push Docker
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD || echo "latest")
          docker build -t $ECR_URI:latest .
          docker tag $ECR_URI:latest $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:latest
          docker push $ECR_URI:$IMAGE_TAG
