name: Terraform + Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5. Terraform Apply (automatically triggers Docker push)
      - name: Terraform Apply
        working-directory: terraform
        run: |
          # Suppress debug logs to avoid wrapper pollution
          TF_LOG=ERROR terraform apply -auto-approve
